plugins {
	id 'com.matthewprenger.cursegradle' version '1.4.0'
}

def target = project.getProperty("target")
def version = file('../version.txt').text.trim()+file("../platform-${target}/version-suffix.txt").text.trim()

def prefix = ""
def artifact = "../platform-${target}/build/libs/ears-${target}-${version}.jar"
def stability = ""
def gameVersions = []
def requires = []
def conflicts = []

switch (target) {
	case "fabric-1.21.11":
		prefix = "FABRIC 1.21.11"
		stability = 'release'
		gameVersions = ['Fabric', 'Quilt', '1.21.11']
		break
	case "fabric-26.1":
		prefix = "FABRIC 26.1/2"
		stability = 'release'
		gameVersions = ['Fabric', 'Quilt', '26.1', '26.1.1', '26.1.2', '26.2']
		break
	case "neoforge-1.21.11":
		prefix = "NEOFORGE 1.21.11"
		stability = 'beta'
		gameVersions = ['NeoForge', '1.21.11']
		break
	case "neoforge-26.1":
		prefix = "NEOFORGE 26.1"
		stability = 'beta'
		gameVersions = ['NeoForge', '26.1', '26.1.1', '26.1.2', '26.2']
		break
	default:
		throw new Exception("Unknown target ${target}")
}

curseforge {
	apiKey = project.getProperty("curseApiKey")
	project {
		id = '412013'
		changelogType = 'html'
		changelog = file('../changelog.html')

		releaseType = stability
		gameVersions.each { addGameVersion(it) }
		
		mainArtifact(file(artifact)) {
			displayName = "[${prefix}] Ears v${version}"

			// it is an error to open this section and not set any relations
			if (!conflicts.isEmpty() || !requires.isEmpty()) {
				relations {
					conflicts.each { incompatible(it) }
					requires.each { requiredDependency(it) }
				}
			}
		}
	}
	options {
		javaVersionAutoDetect = false
//		debug = true
	}
}

task build {}
task assemble {}
