/**
 * The Ears skin data format, in TypeScript.
 *
 * No DOM, no React, no three.js — this is the wire format and nothing else, so it can be used from
 * a worker, a test, or a server just as easily as from the editor.
 *
 * Verified against golden fixtures generated by the Java implementation; see `tests/README.md`.
 */

export * as alfalfa from './alfalfa.js';
export * as png from './png.js';
export * as v0 from './v0.js';
export * as v1 from './v1.js';

export { BitReader, BitWriter } from './bits.js';
export { detect } from './detect.js';
export { write, type SkinFormat, type WriteOptions, type WriteResult } from './encode.js';
export { SkinImage } from './image.js';
export {
	ALFALFA_NONE,
	EAR_ANCHORS,
	EAR_MODES,
	TAIL_MODES,
	WING_MODES,
	disabledFeatures,
	type AlfalfaData,
	type EarAnchor,
	type EarMode,
	type EarsFeatures,
	type TailMode,
	type WingMode,
} from './model.js';
export type { PartialFeatures } from './v1.js';
