package com.unascribed.ears.oracle;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.unascribed.ears.api.Slice;
import com.unascribed.ears.api.features.AlfalfaData;
import com.unascribed.ears.api.features.EarsFeatures;
import com.unascribed.ears.api.features.EarsFeatures.EarAnchor;
import com.unascribed.ears.api.features.EarsFeatures.EarMode;
import com.unascribed.ears.api.features.EarsFeatures.TailMode;
import com.unascribed.ears.api.features.EarsFeatures.WingMode;
import com.unascribed.ears.common.EarsFeaturesWriterV1;
import com.unascribed.ears.common.OracleV0Writer;
import com.unascribed.ears.common.WritableEarsImage;

/**
 * Builds a pack of skins for testing in an actual copy of Minecraft.
 * <p>
 * Everything else in this project is checked against the Java implementation, which is the right
 * authority for the data format — but nothing so far has proved that the mod, built from this tree,
 * draws the right thing on a real player. That needs a person, a launcher and an account, so this
 * generates the skins and a checklist to go with them.
 * <p>
 * Unlike the golden fixtures, these are meant to be <i>looked at</i>: each one isolates a feature
 * against a plain, readable base skin so a mistake is obvious rather than subtle.
 */
public class TestSkins {

	private static final Charset UTF8 = Charset.forName("UTF-8");

	/** A flat, readable base: distinct colour per body part, so geometry errors stand out. */
	private static final int SKIN_TONE = 0xFFE0AC69;
	private static final int SHIRT = 0xFF3F7FA0;
	private static final int TROUSERS = 0xFF3B3F52;
	private static final int FEATURE = 0xFFD8562A;
	private static final int FEATURE_ALT = 0xFF8A4FC4;

	static class Case {
		final String name;
		final String checklist;
		final EarsFeatures.Builder config;
		AlfalfaData alfalfa = AlfalfaData.NONE;
		boolean v0;

		Case(String name, String checklist, EarsFeatures.Builder config) {
			this.name = name;
			this.checklist = checklist;
			this.config = config;
		}

		Case v0() {
			this.v0 = true;
			return this;
		}

		Case with(AlfalfaData alfalfa) {
			this.alfalfa = alfalfa;
			return this;
		}
	}

	public static void main(String[] args) throws Exception {
		if (args.length < 1) {
			System.err.println("usage: TestSkins <output-dir>");
			System.exit(2);
		}
		File outDir = new File(args[0]);
		if (!outDir.exists() && !outDir.mkdirs()) throw new IOException("Could not create "+outDir);

		List<Case> cases = define();
		StringBuilder checklist = new StringBuilder();
		checklist.append("# In-game test pack\n\n");
		checklist.append("Generated by `cd common && ./gradlew testSkins`. Every skin here is written by the same\n");
		checklist.append("code path the manipulator uses, so if one of these renders wrongly in Minecraft, the\n");
		checklist.append("editor's preview is wrong about it too.\n\n");
		checklist.append("## How to run it\n\n");
		checklist.append("1. Build and install: `./build.sh` then `install-test.fish`, or drop a jar from\n");
		checklist.append("   `release/` into a 1.21.11 or 26.1 profile.\n");
		checklist.append("2. Upload a skin below to the account you are testing with, or use a skin-changer mod.\n");
		checklist.append("3. Look at yourself in third person (F5), then check the row.\n\n");
		checklist.append("Compare each against https://skin.daisy.cat with the same file loaded — the preview and\n");
		checklist.append("the game should agree. Where they disagree, the game is right.\n\n");
		checklist.append("| Skin | What to look for | OK? |\n|---|---|---|\n");

		for (Case c : cases) {
			WritableEarsImage img = baseSkin();
			EarsFeatures feat = c.config
					.emissiveSkin(Slice.EMPTY)
					.emissiveWing(Slice.EMPTY)
					.alfalfa(c.alfalfa)
					.build();
			if (c.v0) {
				OracleV0Writer.write(feat, img);
				com.unascribed.ears.common.Alfalfa.write(c.alfalfa, img);
			} else {
				EarsFeaturesWriterV1.write(feat, img);
			}
			Files.write(new File(outDir, c.name+".png").toPath(), Skins.encode(img));
			checklist.append("| `").append(c.name).append(".png` | ").append(c.checklist).append(" |  |\n");
		}

		checklist.append("\n## If something is wrong\n\n");
		checklist.append("Note which skin and what you saw. The fixture name maps straight onto\n");
		checklist.append("`tests/fixtures/`, and `common/src/main/java/com/unascribed/ears/common/EarsRenderer.java`\n");
		checklist.append("is where the geometry for every feature lives.\n");

		Files.write(new File(outDir, "CHECKLIST.md").toPath(), checklist.toString().getBytes(UTF8));
		System.out.println("Wrote "+cases.size()+" test skins and a checklist to "+outDir);
	}

	private static List<Case> define() {
		List<Case> l = new ArrayList<Case>();

		l.add(new Case("01-ears-above", "Ears stand straight up on top of the head, centred", base().earMode(EarMode.ABOVE)));
		l.add(new Case("02-ears-sides", "Ears stick out sideways, level with the top of the head", base().earMode(EarMode.SIDES)));
		l.add(new Case("03-ears-around", "Ears wrap around the top and both sides", base().earMode(EarMode.AROUND)));
		l.add(new Case("04-ears-floppy", "Ears hang down at an angle either side", base().earMode(EarMode.FLOPPY)));
		l.add(new Case("05-ears-tall", "Four stacked segments leaning back, tallest ears", base().earMode(EarMode.TALL)));
		l.add(new Case("06-ears-cross", "Two ears crossed in an X above the head", base().earMode(EarMode.CROSS)));
		l.add(new Case("07-ears-anchor-front", "Ears sit at the FRONT of the head, not the middle",
				base().earMode(EarMode.ABOVE).earAnchor(EarAnchor.FRONT)));
		l.add(new Case("08-ears-anchor-back", "Ears sit at the BACK of the head",
				base().earMode(EarMode.ABOVE).earAnchor(EarAnchor.BACK)));

		l.add(new Case("09-claws", "Claws at both feet and both hands", base().claws(true)));
		l.add(new Case("10-horn", "A single horn tilted forward from the forehead", base().horn(true)));

		l.add(new Case("11-tail-down", "Tail hangs down and back, one segment", base().tailMode(TailMode.DOWN).tailSegments(1)));
		l.add(new Case("12-tail-back", "Tail sticks straight out behind", base().tailMode(TailMode.BACK).tailSegments(1)));
		l.add(new Case("13-tail-up", "Tail points upward", base().tailMode(TailMode.UP).tailSegments(1)));
		l.add(new Case("14-tail-vertical", "Tail is rotated flat, like a fish", base().tailMode(TailMode.VERTICAL).tailSegments(1)));
		l.add(new Case("15-tail-4-bends", "Four segments, visibly bending: down, up, down",
				base().tailMode(TailMode.DOWN).tailSegments(4).tailBends(30, -40, 40, -40)));
		l.add(new Case("16-tail-cross", "Tail is a cross in section, two planes",
				base().tailMode(TailMode.CROSS).tailSegments(2).tailBends(20, 20, 0, 0)));
		l.add(new Case("17-tail-star", "Tail is a star in section, four planes",
				base().tailMode(TailMode.STAR).tailSegments(2).tailBends(20, 20, 0, 0)));
		// v1 cannot store this mode at all, so the writer has to fall back to v0
		l.add(new Case("18-tail-star-overlap-v0", "Star tail with overlapping segments (written as v0)",
				base().tailMode(TailMode.STAR_OVERLAP).tailSegments(2).tailBends(20, 20, 0, 0)).v0());

		l.add(new Case("19-snout-small", "A 1x1x1 nub of a snout", base().snoutWidth(1).snoutHeight(1).snoutDepth(1)));
		l.add(new Case("20-snout-large", "A 7 wide, 4 tall, 6 deep muzzle", base().snoutWidth(7).snoutHeight(4).snoutDepth(6)));
		l.add(new Case("21-snout-offset", "Snout sits low on the face, not centred",
				base().snoutWidth(4).snoutHeight(2).snoutDepth(3).snoutOffset(4)));

		l.add(new Case("22-chest", "A chest bump on the torso, angled down", base().chestSize(1f)));

		l.add(new Case("23-wings-dual", "Two wings, symmetric, animated when walking",
				base().wingMode(WingMode.SYMMETRIC_DUAL)).with(wing()));
		l.add(new Case("24-wings-single", "One wing down the middle of the back",
				base().wingMode(WingMode.SYMMETRIC_SINGLE)).with(wing()));
		l.add(new Case("25-wings-flat", "Wings flat against the back, not angled",
				base().wingMode(WingMode.FLAT)).with(wing()));
		l.add(new Case("26-wings-still", "Wings do NOT flap while walking",
				base().wingMode(WingMode.SYMMETRIC_DUAL).animateWings(false)).with(wing()));

		l.add(new Case("27-cape", "A cape hanging from the shoulders that sways when you move",
				base().capeEnabled(true)).with(cape()));

		l.add(new Case("28-everything", "Ears, claws, horn, bent tail, snout, chest, wings and cape all at once",
				base().earMode(EarMode.AROUND).claws(true).horn(true)
						.tailMode(TailMode.DOWN).tailSegments(3).tailBends(25, 20, 15, 0)
						.snoutWidth(4).snoutHeight(2).snoutDepth(3).snoutOffset(2)
						.chestSize(0.75f)
						.wingMode(WingMode.SYMMETRIC_DUAL)
						.capeEnabled(true))
				.with(wingAndCape()));

		return l;
	}

	private static EarsFeatures.Builder base() {
		@SuppressWarnings("deprecation")
		EarsFeatures.Builder b = EarsFeatures.builder();
		return b.earMode(EarMode.NONE).earAnchor(EarAnchor.CENTER)
				.tailMode(TailMode.NONE).wingMode(WingMode.NONE).animateWings(true);
	}

	private static AlfalfaData wing() {
		Map<String, Slice> m = new LinkedHashMap<String, Slice>();
		m.put("wing", new Slice(Skins.encode(Skins.texture(20, 16, 0x40))));
		return new AlfalfaData(1, m);
	}

	private static AlfalfaData cape() {
		Map<String, Slice> m = new LinkedHashMap<String, Slice>();
		m.put("cape", new Slice(Skins.encode(Skins.texture(20, 16, 0x80))));
		return new AlfalfaData(1, m);
	}

	private static AlfalfaData wingAndCape() {
		Map<String, Slice> m = new LinkedHashMap<String, Slice>();
		m.put("wing", new Slice(Skins.encode(Skins.texture(20, 16, 0x40))));
		m.put("cape", new Slice(Skins.encode(Skins.texture(20, 16, 0x80))));
		return new AlfalfaData(1, m);
	}

	/**
	 * Flat colours per region rather than the fixtures' gradient — these are for looking at, and a
	 * misplaced quad is far easier to spot against a solid colour.
	 */
	private static WritableEarsImage baseSkin() {
		WritableEarsImage img = Skins.baseSkin();
		for (int y = 0; y < 64; y++) {
			for (int x = 0; x < 64; x++) {
				img.setARGB(x, y, 0);
			}
		}
		// head, torso, arms, legs
		fill(img, 0, 0, 32, 16, SKIN_TONE);
		fill(img, 16, 16, 24, 16, SHIRT);
		fill(img, 40, 16, 16, 16, SKIN_TONE);
		fill(img, 32, 48, 16, 16, SKIN_TONE);
		fill(img, 0, 16, 16, 16, TROUSERS);
		fill(img, 16, 48, 16, 16, TROUSERS);
		// the regions Ears samples for its own features
		fill(img, 24, 0, 16, 8, FEATURE);
		fill(img, 56, 28, 8, 16, FEATURE_ALT);
		fill(img, 56, 16, 8, 12, FEATURE);
		fill(img, 56, 0, 8, 8, FEATURE_ALT);
		fill(img, 0, 0, 8, 8, FEATURE);
		fill(img, 16, 48, 4, 4, FEATURE_ALT);
		fill(img, 0, 16, 4, 4, FEATURE_ALT);
		fill(img, 44, 48, 4, 4, FEATURE_ALT);
		fill(img, 52, 16, 4, 4, FEATURE_ALT);
		fill(img, 20, 22, 8, 4, FEATURE);
		fill(img, 56, 44, 8, 4, FEATURE);
		fill(img, 60, 48, 4, 4, FEATURE_ALT);
		return img;
	}

	private static void fill(WritableEarsImage img, int x, int y, int w, int h, int color) {
		for (int dy = 0; dy < h; dy++) {
			for (int dx = 0; dx < w; dx++) {
				img.setARGB(x+dx, y+dy, color);
			}
		}
	}

}
