plugins {
	id 'com.modrinth.minotaur' version '2.9.0'
}

def target = project.getProperty("target")
def baseVersion = file('../version.txt').text.trim()
def versionSuffix = file("../platform-${target}/version-suffix.txt").text.trim()
def version = baseVersion+versionSuffix

def prefix = ""
def artifact = "../platform-${target}/build/libs/ears-${target}-${version}.jar"
def stability = ""
def loaders = []
def gameVersions = []

switch (target) {
	case "fabric-1.21.11":
		prefix = "FABRIC 1.21.11"
		stability = 'release'
		loaders = ['fabric', 'quilt']
		gameVersions = ['1.21.11']
		break
	case "fabric-26.1":
		prefix = "FABRIC 26.1"
		stability = 'release'
		loaders = ['fabric', 'quilt']
		gameVersions = ['26.1', '26.1.1', '26.1.2', '26.2']
		break
	case "neoforge-1.21.11":
		prefix = "NEOFORGE 1.21.11"
		stability = 'beta'
		loaders = ['neoforge']
		gameVersions = ['1.21.11']
		break
	case "neoforge-26.1":
		prefix = "NEOFORGE 26.1"
		stability = 'beta'
		loaders = ['neoforge']
		gameVersions = ['26.1', '26.1.1', '26.1.2', '26.2']
		break
	default:
		throw new Exception("Unknown target ${target}")
}

task build {}
task assemble {}

modrinth {
	token = project.getProperty("modrinthApiKey")
	projectId = 'mfzaZK3Z'
	changelog = file('../changelog.html').text

	versionType = stability
	detectLoaders = false
	
	it.loaders = loaders
	it.gameVersions = gameVersions
	
	uploadFile = file(artifact)
	
	versionName = "[${prefix}] v${version}"
	versionNumber = "${version}+${target}"
}
